name: Release
on:
  push:
    branches:
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
jobs:
  release-local:
    name: release-local
    runs-on: ubuntu-latest
#    if: ${{ github.ref == 'refs/heads/hotfix/*' && !contains(github.event.pull_request.head.ref, 'release/') }}
#    if: ${{ (github.event_name == 'pull_request' && github.base_ref == 'develop') || (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/hotfix/') && !startsWith(github.ref, 'refs/heads/release/')) && !contains(github.event.pull_request.head.ref, 'release/' || 'hotfix/') }}

    # Se ejecuta si la PR es hacia develop y no proviene de una rama de release u hotfix
    if: ${{ !contains(github.event.pull_request.head.ref, 'release/' || 'hotfix/')}}
    environment: local
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      - name: Build and Push docker image
        run: |
          ./gradlew printVersion
          ./gradlew printProjectName
          VERSION=$(./gradlew -q printVersion)
          PROJECT_NAME=$(./gradlew -q printProjectName)
          IMAGE_TAG="$PROJECT_NAME:v$VERSION$SUFFIX"
          docker build --file Dockerfile --build-arg SKIP_TESTS=true --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_HUB_CLIENT_NAME: in2workspace
          SUFFIX: -snapshot
  release-dev:
    name: release-dev
    runs-on: ubuntu-latest
    needs: release-local
#    if: (github.event_name == 'push' && success() && !contains(github.event.pull_request.head.ref, 'release/' || 'hotfix/'))
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      - name: Build and Push docker image
        run: |
          ./gradlew printVersion
          ./gradlew printProjectName
          VERSION=$(./gradlew -q printVersion)
          PROJECT_NAME=$(./gradlew -q printProjectName)
          IMAGE_TAG="$PROJECT_NAME:v$VERSION$SUFFIX"
          docker build --file Dockerfile --build-arg SKIP_TESTS=true --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_HUB_CLIENT_NAME: in2workspace
          SUFFIX: -snapshot
  release-test:
    name: release-test
    runs-on: ubuntu-latest
    needs: release-dev
#    if: (github.event_name == 'push' && success() && !contains(github.event.pull_request.head.ref, 'release/' || 'hotfix/'))
    environment: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      - name: Build and Push docker image
        run: |
          ./gradlew printVersion
          ./gradlew printProjectName
          VERSION=$(./gradlew -q printVersion)
          PROJECT_NAME=$(./gradlew -q printProjectName)
          IMAGE_TAG="$PROJECT_NAME:v$VERSION$SUFFIX"
          docker build --file Dockerfile --build-arg SKIP_TESTS=true --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_HUB_CLIENT_NAME: in2workspace
          SUFFIX: -rc1
  release-prod:
    name: release-prod
    runs-on: ubuntu-latest
    needs: release-test
#    if: (github.event_name == 'push' && success() && !contains(github.event.pull_request.head.ref, 'release/' || 'hotfix/'))
    environment: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      - name: Build and Push docker image
        run: |
          ./gradlew printVersion
          ./gradlew printProjectName
          VERSION=$(./gradlew -q printVersion)
          PROJECT_NAME=$(./gradlew -q printProjectName)
          IMAGE_TAG="$PROJECT_NAME:v$VERSION$SUFFIX"
          docker build --file Dockerfile --build-arg SKIP_TESTS=true --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_HUB_CLIENT_NAME: in2workspace
          SUFFIX: -ga
